 language: python
 python:
    - "3.5"
 env:
    CODACY_PROJECT_TOKEN=343d744f6da04a349a4a831eb93c7a00

 install:
    - pip install -r requirements.txt
    - pip install coveralls codacy-coverage

 script:
    - nosetests -v -w anipy --with-coverage --cover-xml
    - python-codacy-coverage -r coverage.xml

